services:
  ms-event-manager:
    build:
      context: ./ms-event-manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mongodb://db_event:27017/db_event
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db_event

  ms-ticket-manager:
    build:
      context: ./ms-ticket-manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mongodb://db_ticket:27017/db_ticket
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db_ticket

  db_event:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db_event
    ports:
      - "27017:27017"

  db_ticket:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db_ticket
    ports:
      - "27018:27017"